baseURL: https://ai-alignment-and-rationality.github.io/
languageCode: en-us
title: AI alignment and rationality reading group's blog
theme: papermod

params:
  ShowBreadCrumbs: true
  homeInfoParams:
    Title: Welcome to My Snazzy Blog ðŸ´
    Content: > 
      ![horse.jpg](/horse.jpg "He watches")
      sponsored by [Open Philanthropy](https://www.openphilanthropy.org/).

  socialIcons: # optional
    - name: Open Philanthropy
      url: "https://www.openphilanthropy.org/"
    - name: "email"
      url: "mailto:jordnguyen43@gmail.com"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - name: Our Research
      url: /research/
      weight: 4
    - name: Archive
      url: archives/
      weight: 5
    - name: Search
      url: search/
      weight: 10
