baseURL: https://ai-alignment-and-rationality.github.io/
languageCode: en-us
title: Hanoi AI Safety Network
theme: papermod

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
    renderer:
      unsafe: true

languages:
    en:
      LanguageName: "ðŸ‡ºðŸ‡¸"
      weight: 1
      contentDir: content/en
      params:
        languageAltTitle: "English"
      
    vi:
      LanguageName: "ðŸ‡»ðŸ‡³"
      weight: 2
      menu:
        main:
          - identifier: about
            name: "Giá»›i thiá»‡u"
            url: /about/
            weight: 10
          - identifier: events
            name: "Sá»± kiá»‡n"
            url: /events/
            weight: 20
          - identifier: projects
            name: "Dá»± Ã¡n"
            url: /projects/
            weight: 30
          - identifier: logs
            name: "Buá»•i há»p"
            url: /logs/
            weight: 40
          - identifier: activities
            name: "Hoáº¡t Ä‘á»™ng"
            url: /activities/
            weight: 50
          - identifier: members
            name: "ThÃ nh viÃªn"
            url: "/members/"
            weight: 60
      contentDir: content/vi
      params:
        languageAltTitle: "Tiáº¿ng Viá»‡t"
        profilemode:
          enabled: true
          title: "Hanoi AI Safety Network" # optional default will be site title
          subtitle: "CÃ¹ng huá»›ng Ä‘áº¿n an toÃ n AI"
          imageurl: "logo/asrs.png" # optional
          imagetitle: "Hanoi AI Safety Network" # optional
          imagewidth: 250 # custom size
          imageheight: 241 # custom size
          buttons:
            - name: "Giá»›i thiá»‡u"
              url: "/about/"
            - name: "Dá»± Ã¡n"
              url: "/projects/"
            - name: "ThÃ nh viÃªn"
              url: "/members/"

params:
  math: true
  ShowBreadCrumbs: true
  ShowToc: true
  # ShowWordCount: true
  pluralizeListTitles: false
  enableEmoji: true
  label:
    text: "Hanoi AI Safety Network"
    icon: "logo/asrs.png"
    iconHeight: 35

  # homeInfoParams:
  #   Content: > 
  #     ![hasrs.png](logo/hasrs.png "Welcome to ASRS Hanoi!")
  #     sponsored by [Open Philanthropy](https://www.openphilanthropy.org/).
 
  profilemode:
    enabled: true
    title: "Hanoi AI Safety Network" # optional default will be site title
    subtitle: "Dedicated to making AI safer"
    imageurl: "logo/asrs.png" # optional
    imagetitle: "Hanoi AI Safety Network" # optional
    imagewidth: 250 # custom size
    imageheight: 241 # custom size
    buttons:
      - name: About
        url: "/about/"
      - name: Our Projects
        url: "/projects/"
      - name: Our Team
        url: "/members/"
        
  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"

  socialIcons:
    # - name: Open Philanthropy
    #   url: "https://www.openphilanthropy.org/"
    - name: "linkedin"
      url: "https://www.linkedin.com/company/ai-safety-and-rationality-students-hanoi/"
    # - name: "facebook"
    #   url: "https://facebook.com" #PLACEHOLDER
    - name: "github"
      url: "https://github.com/AI-Alignment-and-Rationality"
    - name: "email"
      url: "mailto:jordnguyen43@gmail.com"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Events
      url: /events/
      weight: 2
    - name: Our Work
      url: /projects/
      weight: 3
    - name: Logs
      url: /logs/
      weight: 4
    - name: Our Activities
      url: /activities/
      weight: 5
    - name: Our Team
      url: /members/
      weight: 6
    # - name: Partners
    #   url: /partners/
    #   weight: 5
    # - name: Opportunities
    #   url: /opportunity/
    #   weight: 6
    # - name: Sessions
    #   url: /posts/
    #   weight: 5
    # - name: Archive
    #   url: archives/
    #   weight: 6
    # - name: Search
    #   url: search/
    #   weight: 10
